version: "3"

#docker exec -it <container> mysql -uroot -p
#docker container exec <container> nginx -s reload
#magento setup:install --base-url=http://www.smarties.local/ --db-host=mysql --db-name=www_smarties_local --db-user=myuser --db-password=myuser --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1


services:
    nginx:
        container_name: nginx
        build: d.nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./www:/var/www
            - ./certs:/var/certs
            - ./logs:/var/logs
            - ./d.nginx/conf/www.magento.conf:/etc/nginx/conf.d/magento.conf
        environment:
            - NGINX_SERVER_NAME:www.smarties.local
            - NGINX_PORT:80
        links:
            - php:php
    
    php:
        container_name: php
        build: d.php-fpm
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./logs:/var/logs
#            - ./d.php-fpm/conf/php.ini:/usr/local/etc/php/php.ini
#            - ./d.php-fpm/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        links:
            - php:php

#    mysql:
#        container_name: mysql
#        image: mysql:5.7
#        restart: always
#        ports:
#            - "3306:3306"
#        environment:
#            - MYSQL_ROOT_PASSWORD=passw0rd
#        volumes:
#            - ./d.mysql/data/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
#        links:
#            - php:php
#
#    varnish:
#        image: eeacms/varnish
#        ports:
#            - "6081:6081"
#            - "6085:6085"
#        environment:
#            DNS_ENABLED: "true"
#            BACKENDS_PROBE_INTERVAL: "3s"
#            BACKENDS_PROBE_TIMEOUT: "1s"
#            BACKENDS_PROBE_WINDOW: "3"
#            BACKENDS_PROBE_THRESHOLD: "2"
#            DASHBOARD_USER: "admin"
#            DASHBOARD_PASSWORD: "admin"
#            DASHBOARD_SERVERS: "varnish"
#            DASHBOARD_DNS_ENABLED: "true"
#            PARAM_VALUE: "-p http_resp_hdr_len=65536 -p http_resp_size=98304"
#        links:
#            - "web:web"
#        volumes:
#            - ./conf/varnish/default.vcl:/etc/varnish/conf.d/varnish.vcl